### ISSUE TITLE
Swear word filter

### ISSUE THREAD

**Issue by Samoxive** [Samoxive/SafetyJim#12]
Some users have requested a swear filter to leave that type of moderation to Jim in the past and now we have the ability to make one thanks to the new processor module system.

This processor could scan words in every message and delete the author's message before warning them. This processor could also be customizable as it could be turned on/off and maybe guilds could pick a language so Jim could get rid of swear words in multiple languages. 

If you want to take on this issue, refer to [this example processing module](https://github.com/Samoxive/SafetyJim/blob/master/src/processors/inviteLink/inviteLink.ts) and [the settings command](https://github.com/Samoxive/SafetyJim/blob/master/src/commands/settings/settings.ts) to see how settings and processors are handled within Jim.

**Comment by melmsie** [comment]
meh

**Comment by samwho** [comment]
There's a great library you could use for this in Java that implements the Aho-Corasick trie: https://github.com/robert-bor/aho-corasick. The data structure allows you to give it a list of words and find occurrences of those words in a given string in O(n) time. Perfect for a swear word filter. :)

Example usage: https://github.com/samwho/whobot/blob/master/src/main/java/uk/co/samwho/whobot/util/WordList.java.

**Comment by Samoxive** [comment]
Took longer than expected as it required some refactoring to pave the way for related features but finally solved. Implementation uses Aho-Corasick Trie @samwho suggested to look for exact word matches from user defined word blacklist (default can be found [here](https://github.com/Samoxive/Google-profanity-words/blob/master/list.txt)) and takes user defined action after removing offending messages. As mentioned in #50 Trie objects are cached after construction, caching the word list itself is a non issue as whole guild setting objects are cached as well.

A more advanced implementation would do fuzzy search to combat malicious users trying to undermine the algorithm or blacklisted words with typo however it increases time complexity, false positives and this implementation would be fine for the majority use cases.

Fixes #50 as well, should be deployed soon.
