### ISSUE TITLE
Silent Mode breaks conversations

### ISSUE THREAD

**Issue by lethargilistic** [Samoxive/SafetyJim#28]
Having used the new silent mode for a while, I like that we're hiding the messages from users to avoid public shame. However, I feel like it's breaking conversations. This doesn't matter for warnings, because those have no consequences.However, a kick or a ban means that person is no longer there. The only way people know that is if people congratulate the bot after the action takes place.

I propose having Jim send a message simply saying "Username#1234 was kicked/banned" after deleting the message with the reason. That way, silent mode preserves its "no shame" purpose, but also informs people of the change.

**Comment by Samoxive** [comment]
Sounds like a good suggestion, I understand that this would still hide the reason. I think this would be fit for ban, kick, softban, mute commands? Maybe warnings aren't meant to be public at all? This is totally doable with the next minor release.

**Comment by lethargilistic** [comment]
The active voice is probably better for the message.
Perhaps:
* "[Administrator] kicked [user]"
* "[Administrator asked me to kick [user]"
* "[Administrator told me to kick [user]"

**Comment by Samoxive** [comment]
Good idea, however Jim currently has no functionality voice-chat wise. And for the announcement to work, every online guild member (at least some significant portion of the community) would need to be in a channel Jim sits in. I feel like announcing via text message would be the most convenient solution.

**Comment by lethargilistic** [comment]
["Active voice" is an English grammar term.](https://owl.english.purdue.edu/owl/owlprint/539/) It makes sentences easier to understand than the "passive voice." At this scale, it doesn't matter *that much*, but "It was done" isn't as punchy as "I've done it."

**Comment by Samoxive** [comment]
Right, sorry. We should definitely use that structure for the announcements. @ozankaraali can look into this.

**Comment by Samoxive** [comment]
In both typescript version and java, enabling SilentCommands setting now removes every command message, in rewrite, moderative commands also announce that an action was taken against the target user, this issue can now be closed.
