### ISSUE TITLE
Have Discord-native bans outputted to the moderator log

### ISSUE THREAD

**Issue by aetheryx** [Samoxive/SafetyJim#32]
As of right now, only Jim's bans (so with `-mod ban`) are logged to the audit log. It would be useful to use the [guildBanAdd](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=guildBanAdd) event to log "manually" issues bans (i.e. right click, ban).  
There is no websocket event for kicks (aside from [guildMemberRemove](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=guildMemberRemove), which doesn't necessarily guarantee a kick).  
It would be possible to log mutes aswell with the [guildMemberUpdate](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=guildMemberUpdate) event but that could be a pain in the butt.

**Comment by Samoxive** [comment]
There is already an event for bans and we could use [this method](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchAuditLogs) to fetch last 1-3 audit log entries and determine if the user was kicked or they left on their own. We could also log mutings by listening to role changes but mute is usually used to temporarily mute someone which is done through Jim so we may not need to log them.

**Comment by Samoxive** [comment]
Adding Hacktoberfest label since this is a good newcomer task. Newcomers, please don't hesitate to ask questions about the codebase.

**Comment by liambagge** [comment]
CLAMED!!

**Comment by Samoxive** [comment]
@liambagge What do you mean?

**Comment by liambagge** [comment]
i'm claiming this, marking it that i'm going to do this so no one else steals it ;3

**Comment by Samoxive** [comment]
Implementing this with `GUILD_BAN_ADD` event would mean we only get information about the banned user and nothing else, which makes creating moderator log entries a bit useless. A workaround would be scanning the banned user list or audit log to match the recent ban event and get the metadata that way. Same hack could be used to acquire native kick and mute role assignment events however I am not comfortable with implementing that. 

When moderator log is viewable from the dashboard, Jim will display native bans as well.
