### ISSUE TITLE
Self assignable roles

### ISSUE THREAD

**Issue by melmsie** [Samoxive/SafetyJim#33]
Would be really neat to have a system where users could assign themselves roles.

for instance: `-mod role add nonudes`

Possibly a good thing for hacktoberfest peeps to work on.

**Comment by Samoxive** [comment]
So how would the technical side of this command work? Would guild owners/mods add some roles Jim could let people self-assign? Would anyone be able to self-assign such roles? If not, how would permissions be handled? After we have a clear picture, I feel like this could be added to hacktoberfest issues.

**Comment by melmsie** [comment]
I would say anyone with ban perms should be allowed to add roles, and any roles should be able to be self-assigned by anyone.

Similar to Mantaro's `~>iam nononudes`
