### ISSUE TITLE
Website for your bot

### ISSUE THREAD

**Issue by GreenBayRules** [Samoxive/SafetyJim#42]
I would like to offer my company's service to make a site for your bot that is proffesionally designed and developed. My company is the fastest and the cheapest option. Please DM me on discord if you would like to proceed. 

PackersRuleGoPack#2232

**Comment by Samoxive** [comment]
A website along with a dashboard is already in works over [here](https://github.com/Samoxive/SafetyJim-Client). However, feel free to contribute.
