### ISSUE TITLE
[Suggestion] Permission

### ISSUE THREAD

**Issue by h4sard** [Samoxive/SafetyJim#43]
Hi,
It would be nice to be able to allow some people to use some command just by giving them a specific role instead of having to give them managing role permission.

Thanks.

**Comment by Samoxive** [comment]
With web dashboard becoming a reality, this feature seems doable.

**Comment by LukeM1170** [comment]
This would make the bot different to the others

**Comment by Samoxive** [comment]
I think this goes against my vision for making the bot simple, won't implement.
